# Data Wrangling and Visualization

## Librerias

### Instalacion

### Importacion

In [1]:
import pandas as pd

## Lectura Datos

In [19]:
dfFinalSet = pd.read_csv('FinalSet.csv', dtype = {'codigoencabezado': 'int32'})

dfFinalSet.describe(include = 'all')

,codigoencabezado,idregistro,linkpagina,fecharegistro,administracion,amueblado,antiguedad,banos,habitaciones,estudio,...,moneda,tipo,tipo_vendedor,favoritos,titulo,fecha_creacion,valido_hasta,descripcion,partner_code,user_id
count,520.000000,5.200000e+02,520,520,97.000000,295,178,520.000000,520.000000,520,...,520,520,431,520.000000,520,520,520,520,81,5.200000e+02
unique,NaN,NaN,303,4,NaN,2,7,NaN,NaN,2,...,2,2,2,NaN,292,323,299,300,47,NaN
top,NaN,NaN,https://www.olx.com.gt/item/vendo-en-zona-10-a...,2020-05-20,NaN,No,A estrenar,NaN,NaN,No,...,US$,Apartamento,Inmobiliaria,NaN,APARTAMENTO EN ZONA 15 / ACODI,2020-05-16T03:21:04-06:00,2020-08-13T03:22:20-06:00,"Vivienda abierta (sin muros en el dormitorio),...",11222,NaN
freq,NaN,NaN,5,240,NaN,216,56,NaN,NaN,515,...,377,511,385,NaN,7,8,8,6,4,NaN
mean,260.500000,1.092811e+09,NaN,NaN,434.608247,NaN,NaN,1.988462,2.155769,NaN,...,NaN,NaN,NaN,1.355769,NaN,NaN,NaN,NaN,NaN,3.356498e+07
std,150.255338,1.723419e+07,NaN,NaN,692.991501,NaN,NaN,0.851080,0.853851,NaN,...,NaN,NaN,NaN,3.213406,NaN,NaN,NaN,NaN,NaN,2.283419e+07
min,1.000000,1.033663e+09,NaN,NaN,0.000000,NaN,NaN,1.000000,1.000000,NaN,...,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,4.263970e+06
25%,130.750000,1.100198e+09,NaN,NaN,0.000000,NaN,NaN,1.000000,2.000000,NaN,...,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,2.325799e+07
50%,260.500000,1.100371e+09,NaN,NaN,0.000000,NaN,NaN,2.000000,2.000000,NaN,...,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,2.678192e+07
75%,390.250000,1.100374e+09,NaN,NaN,750.000000,NaN,NaN,2.000000,3.000000,NaN,...,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,5.658755e+07
max,520.000000,1.100380e+09,NaN,NaN,2000.000000,NaN,NaN,5.000000,8.000000,NaN,...,NaN,NaN,NaN,33.000000,NaN,NaN,NaN,NaN,NaN,8.030986e+07

## Data Wrangling

### Conversion Series

In [43]:
dfFinalSet = dfFinalSet.astype({'codigoencabezado': 'str', 
                                'idregistro': 'str',
                                'partner_code': 'str',
                                'user_id': 'str'
                               })

dfFinalSet['fecharegistro'] = pd.to_datetime(dfFinalSet['fecharegistro'], format = "%Y-%m-%d")

dfFinalSet.describe(include = 'all')

,codigoencabezado,idregistro,linkpagina,fecharegistro,administracion,amueblado,antiguedad,banos,habitaciones,estudio,...,moneda,tipo,tipo_vendedor,favoritos,titulo,fecha_creacion,valido_hasta,descripcion,partner_code,user_id
count,520,520,520,520,97.000000,295,178,520.000000,520.000000,520,...,520,520,431,520.000000,520,520,520,520,520,520
unique,520,303,303,4,NaN,2,7,NaN,NaN,2,...,2,2,2,NaN,292,323,299,300,48,91
top,159,1100373436,https://www.olx.com.gt/item/vendo-en-zona-10-a...,2020-05-20 00:00:00,NaN,No,A estrenar,NaN,NaN,No,...,US$,Apartamento,Inmobiliaria,NaN,APARTAMENTO EN ZONA 15 / ACODI,2020-05-16T03:21:04-06:00,2020-08-13T03:22:20-06:00,"Vivienda abierta (sin muros en el dormitorio),...",nan,24012106
freq,1,5,5,240,NaN,216,56,NaN,NaN,515,...,377,511,385,NaN,7,8,8,6,439,93
first,NaN,NaN,NaN,2020-05-14 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
last,NaN,NaN,NaN,2020-05-20 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,434.608247,NaN,NaN,1.988462,2.155769,NaN,...,NaN,NaN,NaN,1.355769,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,692.991501,NaN,NaN,0.851080,0.853851,NaN,...,NaN,NaN,NaN,3.213406,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,1.000000,1.000000,NaN,...,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,1.000000,2.000000,NaN,...,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,2.000000,2.000000,NaN,...,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,750.000000,NaN,NaN,2.000000,3.000000,NaN,...,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,2000.000000,NaN,NaN,5.000000,8.000000,NaN,...,NaN,NaN,NaN,33.000000,NaN,NaN,NaN,NaN,NaN,NaN

### Registros Unicos
Se obtendran solo los ultimos registros obtenidos para cada id de registro (idregistro)

In [47]:
dfAnalisisSet = dfFinalSet.loc[dfFinalSet.reset_index().groupby(['idregistro'])['fecharegistro'].idxmax()]

dfAnalisisSet

,codigoencabezado,idregistro,linkpagina,fecharegistro,administracion,amueblado,antiguedad,banos,habitaciones,estudio,...,moneda,tipo,tipo_vendedor,favoritos,titulo,fecha_creacion,valido_hasta,descripcion,partner_code,user_id
323,324,1033662607,https://www.olx.com.gt/item/se-alquila-apartam...,2020-05-20,NaN,No,NaN,3,3,No,...,US$,Apartamento,Inmobiliaria,1,Se alquila Apartamento en zona 16 en el sector...,2020-04-29T14:13:30-06:00,2020-07-28T14:13:30-06:00,"Apartamento para estrenar muy cerca a Cayalá, ...",nan,15462053
425,426,1044844084,https://www.olx.com.gt/item/apartamento-en-zon...,2020-05-20,NaN,No,NaN,1,1,No,...,US$,Apartamento,Inmobiliaria,0,APARTAMENTO EN ZONA 10 / ACODI,2020-05-15T18:33:41-06:00,2020-08-13T18:33:41-06:00,Edificio\n– Piscina\n– Gimnasio\n– Área verde ...,nan,24012106
426,427,1044844541,https://www.olx.com.gt/item/apartamento-en-lir...,2020-05-20,NaN,NaN,NaN,2,3,No,...,US$,Apartamento,Inmobiliaria,0,"APARTAMENTO EN LIRIOS, ZONA 16 / ACODI",2020-05-15T18:32:13-06:00,2020-08-13T18:32:13-06:00,– Área de construcción: 120 m2\n\n– Sala\n– Co...,nan,24012106
427,428,1044963404,https://www.olx.com.gt/item/apartamento-en-lir...,2020-05-20,NaN,No,NaN,2,3,No,...,US$,Apartamento,Inmobiliaria,0,"APARTAMENTO EN LIRIOS, ZONA 16 / ACODI",2020-05-15T18:27:15-06:00,2020-08-13T18:27:15-06:00,Edificio\n– Piscina\n– Gimnasio\n– Áreas verde...,nan,24012106
428,429,1045112739,https://www.olx.com.gt/item/apartamento-torre-...,2020-05-20,NaN,NaN,NaN,2,2,No,...,US$,Apartamento,Inmobiliaria,1,"APARTAMENTO TORRE CAPRESE, ZONA 15 OPCIÓN 3/ACODI",2020-05-15T18:10:32-06:00,2020-08-13T18:10:32-06:00,Edificio\n– De 11 Niveles\n– 2 Elevadores\n– 2...,nan,24012106
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308,309,1100379608,https://www.olx.com.gt/item/bonito-apartamento...,2020-05-20,NaN,NaN,Entre 5 y 10 años,2,3,No,...,Q,Apartamento,Inmobiliaria,0,Bonito Apartamento Zona 1 Torre Entre Arboles(...,2020-05-20T07:02:16-06:00,2020-08-18T07:00:13-06:00,Bonito Apartamento Zona 1 Torre Entre Arboles(...,nan,65046099
307,308,1100379612,https://www.olx.com.gt/item/precioso-apartamen...,2020-05-20,NaN,NaN,Entre 5 y 10 años,2,3,No,...,Q,Apartamento,Inmobiliaria,0,"Precioso Apartamento Zona 1, Torre Entre Arbol...",2020-05-20T07:06:09-06:00,2020-08-18T07:06:09-06:00,"Precioso Apartamento Zona 1, Torre Entre Arbol...",nan,65046099
306,307,1100379641,https://www.olx.com.gt/item/alquilo-apartament...,2020-05-20,NaN,No,NaN,1,2,No,...,Q,Apartamento,Dueño Directo,0,Alquilo apartamento a 3 cuadras palacio nacion...,2020-05-20T08:16:04-06:00,2020-08-18T08:16:04-06:00,Apartamento pequeño a 3 cuadras Palacio Nacion...,nan,17034186
305,306,1100379667,https://www.olx.com.gt/item/vendo-bonitos-apar...,2020-05-20,NaN,NaN,Entre 5 y 10 años,2,3,No,...,Q,Apartamento,Inmobiliaria,0,VENDO BONITOS APARTAMENTOS EN ZONA 1 CON FINAN...,2020-05-20T08:48:57-06:00,2020-08-18T08:48:57-06:00,VENDO BONITOS APARTAMENTOS EN ZONA 1\n\n* HIST...,nan,65046099
304,305,1100379688,https://www.olx.com.gt/item/vendo-bonito-apart...,2020-05-20,NaN,NaN,Entre 5 y 10 años,2,2,No,...,Q,Apartamento,Inmobiliaria,0,Vendo Bonito Apartamento en Zona 1 Historico 1...,2020-05-20T09:11:55-06:00,2020-08-18T09:11:55-06:00,"Bonito Apartamento en Zona 1 Historico 1, a la...",nan,65046099